import {
  runelightStudioComponentCardTitleGap,
  runelightStudioComponentCardTitleHeight,
  runelightStudioComponentCardTitleScreenGap,
  runelightStudioComponentCardTitleScreenHeight,
  runelightStudioComponentFrameChromeHeight,
  runelightStudioComponentFrameGridGap,
  runelightStudioComponentFrameGridMinScale,
  runelightStudioComponentFrameLabelGap,
  runelightStudioComponentFrameLabelMinHeight,
  runelightStudioComponentFrameLabelScreenGap,
  runelightStudioComponentFrameLabelScreenMinHeight,
  runelightStudioComponentFrameMismatchBorderOutset,
  runelightStudioFrameGridMaxSide,
} from "@runelight/core"

import type { StudioViewportPreset } from "./client"

export function studioFrameGridMaxSide(viewportPreset: StudioViewportPreset, frameCount: number): number {
  return runelightStudioFrameGridMaxSide(viewportPreset, frameCount)
}

export const studioComponentFrameGridGap = runelightStudioComponentFrameGridGap
export const studioComponentCardTitleScreenGap = runelightStudioComponentCardTitleScreenGap
export const studioComponentCardTitleScreenHeight = runelightStudioComponentCardTitleScreenHeight
export const studioComponentFrameLabelScreenGap = runelightStudioComponentFrameLabelScreenGap
export const studioComponentFrameLabelScreenMinHeight = runelightStudioComponentFrameLabelScreenMinHeight
export const studioComponentCardTitleGap = runelightStudioComponentCardTitleGap
export const studioComponentCardTitleHeight = runelightStudioComponentCardTitleHeight
export const studioComponentFrameLabelGap = runelightStudioComponentFrameLabelGap
export const studioComponentFrameLabelMinHeight = runelightStudioComponentFrameLabelMinHeight
export const studioComponentFrameChromeHeight = runelightStudioComponentFrameChromeHeight
export const studioComponentFrameGridMinScale = runelightStudioComponentFrameGridMinScale
export const studioComponentFrameMismatchBorderOutset = runelightStudioComponentFrameMismatchBorderOutset
